development:
  adapter: postgresql

test:
  adapter: postgresql

production:
  adapter: postgresql
  # url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: Walker_production
